export { FrameworkButtonComponent } from './framework-button/framework-button.component'
export {GithubComponent } from './github/github.component'
export { LinkedinComponent } from './linkedin/linkedin.component'
export { MuteButtonComponent} from './mute-button/mute-button.component'
export { PaypalComponent } from './paypal/paypal.component'