name: Deploy to Preview Channel

on:
  push:
    branches-ignore:
     - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_EA11E }}'
          expires: 3d
          projectId: portfolio-ea11e
          channelId: 'preview-branch-${{ github.event.push.head.ref }}'
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
